### ISSUE TITLE
Typo in modeling_schema.yaml: wave_seeds

### ISSUE THREAD

**Issue by mlidGWT** [WISDEM/WEIS#245]
## Description
The [modeling_schema.yaml](weis/inputs/modeling_schema.yaml) file has a typo for one of the inputs: 
[wave_seed](https://github.com/WISDEM/WEIS/blob/5332c31ebcc658f269c16a175656a8b35f4fe79c/weis/inputs/modeling_schema.yaml#L2950C34-L2950C34) should instead be `wave_seeds`, plural. When I added that parameter as written in the schema to my file, OpenFAST/WEIS failed with the error below. 

When I updated the parameter to `wave_seeds` WEIS ran as expected, though still did not take the seed I was defining:
- in my `modeling_options.yaml` in the DLC definition block I have `wave_seeds: [2035833227]`
- But in my `case_matrix.txt` file, I see  `HydroDyn \n WaveSeed1 \n 304524126` (\n used to indicate new lines for compactness)
- I have also tried running with `HydroDyn:  WaveSeed1: 2035833227` in the `Level3` section of the file, but that also does not seem to have any effect, however these are separate issues from the typo, so only noting them here for the time being. 
 
### Steps to reproduce issue
Add `wave_seed` to `modeling_options.yaml` file and run WEIS. 

### Current behavior
WEIS fails with error: 
>Traceback (most recent call last):
  File "/Users/meglidrbauch/Software/LoadsRuns/SimulationLibrary/1002.1.2_MEA/IEA15MW_Baseline/DetailedRuns/L62/weis_driver.py", line 15, in <module>
    wt_opt, modeling_options, opt_options = run_weis(fname_wt_input, fname_modeling_options, fname_analysis_options)
  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/runWEIS.py", line 20, in run_weis
    wt_initial = WindTurbineOntologyPythonWEIS(fname_wt_input, fname_modeling_options, fname_opt_options)
  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/gc_LoadInputs.py", line 26, in __init__
    self.set_weis_data()
  File "/Users/meglidrbauch/Software/WEIS/weis/glue_code/gc_LoadInputs.py", line 146, in set_weis_data
    dlc_generator.generate(DLCopt['DLC'], DLCopt)
  File "/Users/meglidrbauch/Software/WEIS/weis/dlc_driver/dlc_generator.py", line 221, in generate
    getattr(self, func_name)(options) # calls self.generate_1p1(options)
  File "/Users/meglidrbauch/Software/WEIS/weis/dlc_driver/dlc_generator.py", line 700, in generate_6p2
    _, wind_seeds, wave_seeds, wind_heading, wave_Hs, wave_Tp, wave_gamma, wave_heading, _ = self.get_metocean(options)
  File "/Users/meglidrbauch/Software/WEIS/weis/dlc_driver/dlc_generator.py", line 180, in get_metocean
    wave_seeds = self.get_wave_seeds(options, wind_speeds)
  File "/Users/meglidrbauch/Software/WEIS/weis/dlc_driver/dlc_generator.py", line 129, in get_wave_seeds
    wave_seeds = np.array( [int(m) for m in options['wave_seeds']] )

### Expected behavior
WEIS runs. 

I know this is a simple fix and I apologize for not simply making the correction and submitting a commit myself, but I am not confident with GitHub and pull requests/commits and don't want to risk causing a bigger issue. I'll get there soon. :)

**Comment by dzalkind** [comment]
Hi Meg, thanks for the tip!   Let's go with `wave_seeds` as the correct input.  The HydroDyn input will be overwritten by the DLC generator.  If you want a fixed seed, you should be able to use a single `wave_seeds` input.

This has been linked to the `phase2` PR.
