### ISSUE TITLE
Error when running weis_driver.py from 03_NREL5MW_OC3_spar

### ISSUE THREAD

**Issue by MalikSpahic** [WISDEM/WEIS#326]
Hello,

I am making this ticket, because after following the installation procedure given in the github for WEIS on a virtual machine and linux environment, I get an error when I run the script 'weis_driver.py' from the folder '03_NREL5MW_OC3_spar'. However, I am not witnessing any error when I run 'weis_freq_driver.py'.

Please, find below the description of the bug:

## Description
_Describe the bug here_

 '<' model '>' '<' class WindPark '>': Attempted to connect from 'aeroelastic.hub_Fxyz' to 'drivese_post.F_hub', but 'drivese_post.F_hub' doesn't exist. Perhaps you meant to connect to one of the following inputs: ['drivese_post.hub_I', 'drivese_post.F_mb2', 'drivese_post.F_mb1'].
   '<' model '>' '<' class WindPark '>': Attempted to connect from 'aeroelastic.hub_Mxyz' to 'drivese_post.M_hub', but 'drivese_post.M_hub' doesn't exist. Perhaps you meant to connect to one of the following inputs: ['drivese_post.hub_I', 'drivese_post.M_mb2', 'drivese_post.M_mb1'].

Could you help me fixing it ?

Kind regards,

Malik

**Comment by dzalkind** [comment]
Hi Malik,

Do you mind posting your conda environment?  `conda list` 

I suspect the issue is that an older version of wisdem was installed.  Please try `conda install wisdem=3.18`.

I will post a fix to the environment.yml file so this issue does not occur in the future.  Thank you for posting!

Best, Dan

**Comment by MalikSpahic** [comment]
Hey Dan,

Thank you for your fast answer ! Sure here is my conda environment :

# packages in environment at /home/ubuntu/anaconda3/envs/envWeis:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
ampl-mp                   3.1.0             h2cc385e_1006    conda-forge
anyio                     4.6.2.post1              pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     24.2.0             pyh71513ae_0    conda-forge
babel                     2.16.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2                    pypi_0    pypi
contourpy                 1.3.0           py312h68727a3_2    conda-forge
control                   0.10.1             pyhd8ed1ab_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
dash                      2.18.1             pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 1.6.0                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-mantine-components   0.14.6                   pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
dbus                      1.13.6               h5008d03_3    conda-forge
dearpygui                 2.0.0                    pypi_0    pypi
debugpy                   1.8.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.9              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
double-conversion         3.3.0                h59595ed_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0                    pypi_0    pypi
expat                     2.6.3                h5888daf_0    conda-forge
fastjsonschema            2.20.0                   pypi_0    pypi
fatpack                   0.7.7              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          mpi_openmpi_h99e62ba_10    conda-forge
flask                     3.0.3              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.54.1          py312h66e93f0_0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
git                       2.47.0          pl5321h59d505e_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
h11                       0.14.0                   pypi_0    pypi
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf5                      1.14.4          mpi_openmpi_h39ae36c_1    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.6                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hypre                     2.31.0          mpi_openmpi_h834c3d3_1    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipopt                     3.14.16             h122424a_10    conda-forge
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.28.0                   pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jedi                      0.19.1                   pypi_0    pypi
jenn                      1.0.8              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.25                   pypi_0    pypi
jsonmerge                 1.9.2              pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jupyter                   1.1.1                    pypi_0    pypi
jupyter-client            8.6.3                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-lsp               2.2.5                    pypi_0    pypi
jupyter-server            2.14.2                   pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyterlab                4.2.5                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.3                   pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py312h68727a3_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libclang-cpp19.1          19.1.2          default_hb5137d0_0    conda-forge
libclang13                19.1.2          default_h9c6a7e4_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libdrm                    2.4.123              hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libegl                    1.7.0                ha4b6fd6_1    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgl                     1.7.0                ha4b6fd6_1    conda-forge
libglib                   2.82.1               h2ff4ddf_1    conda-forge
libglvnd                  1.7.0                ha4b6fd6_1    conda-forge
libglx                    1.7.0                ha4b6fd6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
libllvm19                 19.1.2               ha7bfdaf_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.10.0               h4bc722e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.27          openmp_h25fa9fd_1    conda-forge
libopengl                 1.7.0                ha4b6fd6_1    conda-forge
libosqp                   0.6.3                h6a678d5_0
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     17.0                 h04577a9_4    conda-forge
libptscotch               7.0.5                hb0c3d77_2    conda-forge
libqdldl                  0.1.7                hcb278e6_0    conda-forge
libscotch                 7.0.5                h3428b0d_2    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libspral                  2024.05.08           h831f25b_3    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h2c5496b_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
llvm-openmp               19.1.2               h024ca30_0    conda-forge
markupsafe                3.0.1           py312h178313f_1    conda-forge
marmot-agents             0.2.5                    pypi_0    pypi
mat4py                    0.6.0              pyhd8ed1ab_0    conda-forge
matplotlib                3.9.2           py312h7900ff3_1    conda-forge
matplotlib-base           3.9.2           py312hd3ec401_1    conda-forge
matplotlib-inline         0.1.7                    pypi_0    pypi
mdolab-baseclasses        1.8.0              pyhd8ed1ab_0    conda-forge
meson                     1.5.2                    pypi_0    pypi
metis                     5.1.0             hd0bcaf9_1007    conda-forge
mistune                   3.0.2                    pypi_0    pypi
moorpy                    1.1.0              pyhd8ed1ab_0    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    4.0.1           py312h5ca6011_0    conda-forge
mumps-include             5.7.3                ha770c72_5    conda-forge
mumps-mpi                 5.7.3                h7b4c042_5    conda-forge
mumps-seq                 5.7.3                hcd84eb1_5    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              9.0.1                h266115a_1    conda-forge
mysql-libs                9.0.1                he0572af_1    conda-forge
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.4                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.4.1              pyhd8ed1ab_0    conda-forge
ninja                     1.11.1.1                 pypi_0    pypi
nlopt                     2.8.0           py312h69683c5_2    conda-forge
notebook                  7.2.2                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numpy                     1.26.4          py312heda63a1_0    conda-forge
openfast                  3.5.3                h4226df5_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openldap                  2.6.8                hedd0468_0    conda-forge
openmdao                  3.35.0             pyhd8ed1ab_0    conda-forge
openmpi                   5.0.5              h9a79eee_101    conda-forge
openpyxl                  3.1.5           py312h710cb58_1    conda-forge
openraft                  1.3.1              pyhd8ed1ab_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
orjson                    3.10.7          py312hf008fa9_0    conda-forge
osqp                      0.6.7.post0     py312h1d6d2e6_0    conda-forge
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hf9745cd_1    conda-forge
pandocfilters             1.5.1                    pypi_0    pypi
parmetis                  4.0.3             h2554033_1006    conda-forge
parso                     0.8.4                    pypi_0    pypi
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pcrunch                   1.1.0              pyhd8ed1ab_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
petsc                     3.22.0          real_h0fd7d50_102    conda-forge
petsc4py                  3.22.0          py312he60148a_0    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pillow                    11.0.0          py312h7b63e92_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6                    pypi_0    pypi
plotly                    5.24.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
prometheus-client         0.21.0                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydoe3                    1.0.4              pyhd8ed1ab_0    conda-forge
pygments                  2.18.0                   pypi_0    pypi
pyhams                    1.3.0           py312h4c269bc_1    conda-forge
pyoptsparse               2.11.3          py312h0a88f85_0    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pyside6                   6.8.0           py312h91f0f75_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.3.3              pyhd8ed1ab_0    conda-forge
python                    3.12.7          hc5c86c4_0_cpython    conda-forge
python-benedict           0.33.1                   pypi_0    pypi
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fsutil             0.14.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h66e93f0_1    conda-forge
pyzmq                     26.2.0          py312hbf22597_3    conda-forge
qdldl-python              0.1.7.post4     py312hf9745cd_1    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
qt6-main                  6.8.0                h6e8976b_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
retrying                  1.3.3              pyhd8ed1ab_3    conda-forge
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rosco                     2.9.4           py312h66889e3_0    conda-forge
rpds-py                   0.20.0          py312h12e396e_1    conda-forge
ruamel.yaml               0.18.6          py312h66e93f0_1    conda-forge
ruamel.yaml.clib          0.2.8           py312h66e93f0_1    conda-forge
scalapack                 2.2.0                hb5f66cf_2    conda-forge
scikit-learn              1.5.2           py312h7a48858_1    conda-forge
scipy                     1.14.1          py312h7d485d2_0    conda-forge
send2trash                1.8.3                    pypi_0    pypi
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
simpy                     4.1.1              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slycot                    0.6.0           py312hb6c5a0b_2    conda-forge
smt                       2.7.0           py312h25a0e75_0    conda-forge
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.6                      pypi_0    pypi
sqlitedict                2.1.0              pyhd8ed1ab_0    conda-forge
stack-data                0.6.3                    pypi_0    pypi
statsmodels               0.14.4          py312hc0a28a1_0    conda-forge
suitesparse               7.8.2                hb42a789_0    conda-forge
superlu                   5.2.2                h00795ac_0    conda-forge
superlu_dist              9.0.0                h7ac3aea_1    conda-forge
tbb                       2021.13.0            h84d6215_0    conda-forge
tenacity                  9.0.0              pyhd8ed1ab_0    conda-forge
terminado                 0.18.1                   pypi_0    pypi
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tinycss2                  1.3.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.2              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py312h66e93f0_1    conda-forge
traitlets                 5.14.3                   pypi_0    pypi
treon                     0.1.4                    pypi_0    pypi
types-python-dateutil     2.9.0.20241003           pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
unixodbc                  2.3.12               h661eb56_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wayland                   1.23.1               h3e06ad9_0    conda-forge
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 24.8.0                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
weis                      1.3                      pypi_0    pypi
werkzeug                  3.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.13                   pypi_0    pypi
wisdem                    3.17.0          nompi_h38177b6_101    conda-forge
xcb-util                  0.4.1                hb711507_2    conda-forge
xcb-util-cursor           0.1.5                hb9d3cd8_0    conda-forge
xcb-util-image            0.4.0                hb711507_2    conda-forge
xcb-util-keysyms          0.4.1                hb711507_0    conda-forge
xcb-util-renderutil       0.3.10               hb711507_0    conda-forge
xcb-util-wm               0.4.2                hb711507_0    conda-forge
xkeyboard-config          2.43                 hb9d3cd8_0    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxcomposite        0.4.6                hb9d3cd8_2    conda-forge
xorg-libxcursor           1.2.2                hb9d3cd8_0    conda-forge
xorg-libxdamage           1.1.6                hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.1                hb9d3cd8_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxrandr            1.5.4                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-libxtst              1.2.5                hb9d3cd8_3    conda-forge
xorg-libxxf86vm           1.1.5                hb9d3cd8_4    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.5                h3b0a872_6    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

As you guessed, it seems that the wisdem version that I was using was old (wisdem v. 3.17). But now, I got a new error for both python scripts "weis_driver.py" and "weis_freq_driver.py" : 

Using weis.aeroelasticse in rosco.toolbox...
Traceback (most recent call last):
  File "/home/ubuntu/WEIS/examples/03_NREL5MW_OC3_spar/weis_freq_driver.py", line 5, in <module>
    from weis.glue_code.runWEIS     import run_weis
  File "/home/ubuntu/WEIS/weis/glue_code/runWEIS.py", line 4, in <module>
    from weis.glue_code.gc_LoadInputs     import WindTurbineOntologyPythonWEIS
  File "/home/ubuntu/WEIS/weis/glue_code/gc_LoadInputs.py", line 10, in <module>
    from wisdem.commonse.mpi_tools              import MPI
ModuleNotFoundError: No module named 'wisdem.commonse.mpi_tools'

Could you help me to solve it ?

Kind regards,

Malik

**Comment by dzalkind** [comment]
Hi Malik,

Please pull in the latest `main` branch, where we have updated these `wisdem` imports.

Best, Dan

**Comment by MalikSpahic** [comment]
Hi Dan,

Thank you for your answer and sorry for the late reply (I was on vacations soon after your message). I downloaded the 1.4 version and the error is not present for this example anymore :)

Thank you for fixing it that fast !

Kind regards,

Malik
